### ISSUE TITLE
Paper 1: future wide field survey predictions

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#100]
Add some quantitative future predictions for what SW system can achieve for e.g. EUCLID, LSST etc.

**Comment by drphilmarshall** [comment]
@aprajita @chrislintott can you please take a quick look at the new text in section 6 of paper 1, about future surveys? Also @chrislintott I use the word "gamified" at one point so you might like to police that!

**Comment by drphilmarshall** [comment]
PS. The new text is in blue in the pdf!

**Comment by aprajita** [comment]
Thanks text is OK, could still have more survey specific numbers from LSST or EUCLID expectations but I don't think we need to worry about this now. For future consideration:
- could be more specific e.g. 10^8 images (number of expected LRG with m<XX expected in the LSST Gold Sample) ... 
- 10^6 images from lens finding algorithms - where does this come from (expected yield from automated searches like ring finder on the whole LSST survey, or some fraciotn of the area etc)
should also mention that as we get better machine learning code, are we ina position to reduce this number significantly - and does that allow us to focus users on more skilled work e.g. image marking, lens modelling etc…
am reopening as I am not sure you will get notification if i comment without reopening

**Comment by chrislintott** [comment]
Altered the text to be more explicit (I think we should avoid 'gamified' as that means something very different from the limited task allocation you're talking about here)
