### ISSUE TITLE
Consistency between Paper 1 and Paper 2

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#105]
Need a section in paper 2 with a recap of paper 1 - can be mostly written now, with details later. Main thing is to make papers consistent - so this could be done as a final step. But @anupreeta27 can draft the section in paper 2 already.

**Comment by drphilmarshall** [comment]
Some notes on consistency between paper 1 and 2, after reading @anupreeta27's draft of sw-cfhtls:

* [ ] Let's make some macros for "stage 1" and "stage 2" and have both papers use them
* [ ] There is some repeated text that can be compressed (eg paper 2 image presentation, paper 1 data)
* [ ] Let's use different terms for the "skill" quantities being used. How about "Power" for the kick size used in Paper 2?
* [ ] It could be good to include more cross-references to the results of Paper 1 in Paper 2, in particular when contrasting the system performance on known lenses/candidates with the training set

**Comment by anupreeta27** [comment]
@drphilmarshall  is this an open issue?

**Comment by drphilmarshall** [comment]
Yes - I'll close it when I've finished reading through both papers.

**Comment by anupreeta27** [comment]
@drphilmarshall  i have revised keywords for paper 2 following the instructions given here:
http://oxfordjournals.org/our_journals/mnrasl/for_authors/mnraskeywords.pdf

**Comment by drphilmarshall** [comment]
I think the papers are looking pretty consistent now - just need to add a note in paper 2 about the confusion matrix being M in paper 1.

**Comment by drphilmarshall** [comment]
(Note that this issue will get closed when you merge PR 203, Anu.)
