### ISSUE TITLE
"Skill" vs "Power" in Paper 2

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#110]
How about we keep "Skill" for the Paper 1 definition, and adopt "Power" for the kick size used in Paper 2? What do you think, @anupreeta27 and @aprajita?

**Comment by drphilmarshall** [comment]
OK - I will go through the appendix and try and disentangle "skill" from "Skill" ! :-)

**Comment by drphilmarshall** [comment]
OK, git pull, @anupreeta27, and let me know what you think!

**Comment by anupreeta27** [comment]
Looks fine. I will adapt other text in the paper accordingly.
