### ISSUE TITLE
Figure 3 (dud gallery) needs panels without insets

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#111]
@cpadavis would you mind digging these images up (the originals, without insets) and replacing 0.png-3.png, please? Thanks!

**Comment by cpadavis** [comment]
(obvious) note to self: next time when making the gallery, make sure your filenames make it easy to recover the original image!

**Comment by drphilmarshall** [comment]
Thanks Chris! :-)
