### ISSUE TITLE
Simpler completeness-purity plot

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#113]
Originally we made this plot for diagnostic purposes, but it's pretty busy. I think we can mention the results for different lens types in the text, or just defer all that discussion to paper 2, and just show the solid stage 1 all and stage 2 all curves on the completeness-purity plot. The inset is still helpful, since it shows as reaching a particular standard: 90% completeness at 30% purity, You might have to increase the axis ranges a little on the inset to show this though. Woudl you mind making a simpler version and adding it to the repo and latex file with a different name, please? Thanks!

**Comment by cpadavis** [comment]
current iteration:

![image](https://cloud.githubusercontent.com/assets/1781988/7056368/ef7f121a-ddff-11e4-9c43-d9916c55d3c7.png)

**Comment by drphilmarshall** [comment]
Looks good, thanks!
