### ISSUE TITLE
SW atlas: catalog schema

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#116]
Hey @cpadavis can you check in what you have on the SW atlas, so we can see how to merge in @aprajita's detailed labels? She mainly needs the schema right now, to make sure the matching can be done easily. (Image ID plus pixel coordinates is probably the way to go - but which image ID? etc)

**Comment by cpadavis** [comment]
I'll attempt to get that all pushed today. Basically to trace to the fields
I keep track of the ZooID and also the 'ID' parameter that swap has (no
idea where that comes from). So ZooID plus x,y pixel coordinates should be
totally sufficient for matching.

**Comment by cpadavis** [comment]
Just to be clear, "ZooID"s start with "ASW". Is that how subjects are logged from the visapp as well, @aprajita?

**Comment by anupreeta27** [comment]
@cpadavis i can't remember but probably visapp has the cfhtls_id. anyway, its fine as long as we get one id, i can extract the other ids and send it to you and aprajita.

**Comment by cpadavis** [comment]
I can also convert between cfhtls and zooids

**Comment by cpadavis** [comment]
catalog code merged in
