### ISSUE TITLE
Cite fitsjs

### ISSUE THREAD

**Issue by kapadia** [drphilmarshall/SpaceWarps#119]
@drphilmarshall Let's practice software citation in SpaceWarps.

I just generated a DOI for [fitsjs](https://github.com/astrojs/fitsjs) - `10.5281/zenodo.16707`. Do you mind adding this to the upcoming SpaceWarps paper?

**Comment by kapadia** [comment]
Here's the bibtex:

    @misc{amit_kapadia_2015_16707,
      author       = {Amit Kapadia},
      title        = {fitsjs: 0.6.6},
      month        = apr,
      year         = 2015,
      doi          = {10.5281/zenodo.16707},
      url          = {http://dx.doi.org/10.5281/zenodo.16707}
    }

**Comment by aprajita** [comment]
good idea!

**Comment by kapadia** [comment]
@aprajita :smiley:

**Comment by drphilmarshall** [comment]
I'll get on this as soon as I can - my laptop just failed though...

**Comment by aprajita** [comment]
oh no!!!… can you recover?

**Comment by drphilmarshall** [comment]
Yes! There's always a plan B, somewhere...

**Comment by anupreeta27** [comment]
@drphilmarshall hope its not on your laptop! :wink:

**Comment by drphilmarshall** [comment]
Hah! :-)

Including ref to fitsjs now.

**Comment by kapadia** [comment]
Thanks everyone. @drphilmarshall hope you're back up to speed!
