### ISSUE TITLE
Bibtex for IBCC paper

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#122]
Hi @edwinrobots ! We'd like to cite your IBCC paper please - can you give us the correct bibtex entry please? I put a placeholder in [doc/references.bib](https://github.com/drphilmarshall/SpaceWarps/blob/master/doc/references.bib) for you, should be easy to fill in the gaps. Thanks!

**Comment by drphilmarshall** [comment]
Hi @edwinrobots, @arfon: 

Is the following the right bibtex for the IBCC paper? Or did it appear in a journal somewhere?

    @ARTICLE{IBCC,
    author = {{Simpson}, E. and {Roberts}, S. and {Psorakis}, I. and {Smith}, A.},
    title = "{Dynamic Bayesian Combination of Multiple Imperfect Classifiers}",
    journal = {ArXiv e-prints},
    archivePrefix = "arXiv",
    eprint = {1206.1831},
    primaryClass = "math.ST",
    keywords = {Mathematics - Statistics Theory, Astrophysics - Instrumentation and Methods for Astrophysics},
     year = 2012,
     month = jun,
     adsurl = {http://adsabs.harvard.edu/abs/2012arXiv1206.1831S},
    adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by edwinrobots** [comment]
Hi Phil,

Sorry I missed you first email! I have been using this, as it's inside a
book series:

@incollection{IBCC,
  title={{Dynamic Bayesian Combination of Multiple Imperfect Classifiers}},
  author={Simpson, Edwin and Roberts, Stephen and Psorakis, Ioannis and
Smith, Arfon},
  booktitle={Intelligent Systems Reference Library series: Decision Making
and Imperfection},
  pages={1--35},
  year={2013},
  publisher={Springer}
}


Thanks,
Edwin.

**Comment by drphilmarshall** [comment]
On Mon, Apr 20, 2015 at 7:25 AM, edwinrobots <notifications@github.com>
wrote:

> @incollection{IBCC,
> title={{Dynamic Bayesian Combination of Multiple Imperfect Classifiers}},
> author={Simpson, Edwin and Roberts, Stephen and Psorakis, Ioannis and
> Smith, Arfon},
> booktitle={Intelligent Systems Reference Library series: Decision Making
> and Imperfection},
> pages={1--35},
> year={2013},
> publisher={Springer}
> }
>

​Great, thanks Edwin!​
