### ISSUE TITLE
References

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#123]
Paper II &2.2
"In the thesis dissertation of ?, 9 promising and 2 low probability candidates are reported which were discovered serendipitiously."

Could it be 
Cosmic applications of gravitational lens assisted spectroscopy (GLAS)
Thanjavur, Karunananth G. 
https://dspace.library.uvic.ca:8443/handle/1828/1261
https://dspace.library.uvic.ca:8443/bitstream/handle/1828/1261/thesis_fini.pdf?sequence=1&isAllowed=y

**Comment by anupreeta27** [comment]
Thanks @ccld. The reference is actually added to the bibtex file, it just didn't appear properly in the pdf. I will fix it.
