### ISSUE TITLE
candidates lurking in TALK P< 0.3

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#124]
To be inspected along with four known lenses of P value <0.3 

zooid		P	Nclass	image				comment
ASW00097xm	0.296	47	5183f151e4bb21021906906a.png	double
ASW0006i3r	0.294	50	5183f151e4bb21021904a127.png	model
ASW0009bq8	0.277	43	5183f151e4bb21021906a3a0.png	known
ASW0006k9m	0.274	50	5183f151e4bb21021904ac1a.png
ASW0007qve	0.254	50	5183f151e4bb2102190583ca.png
ASW00000k1	0.254	50	5183f151e4bb2102190002d1.png
ASW0008cu1	0.238	49	5183f151e4bb21021905f2f9.png	known
ASW00054l3	0.230	21	5183f151e4bb21021903a677.png	exotica
ASW0006hoa	0.218	49	5183f151e4bb210219049efa.png	known
ASW0000o2y	0.206	49	5183f151e4bb2102190079ea.png	or ASW0000pkk
ASW0003yal	0.204	50	5183f151e4bb21021902d05d.png	to model?
ASW0005saz	0.195	50	5183f151e4bb210219041e8b.png	known

**Comment by anupreeta27** [comment]
ASW00097xm (double) and ASW0005saz (known) look like the most promising ones among all. I have seen the ASW00054l3 (exotica) before but worth noting it here. thanks!

**Comment by aprajita** [comment]
thanks claude
i'll be looking over the entire sample again to see whether we've missed anything at P<0.3 among other things, this list is v useful for me to check against as well.

**Comment by ccld** [comment]
I've to had some frames commented by one of you for a second inspection and another known:
zooid P Nclass image comment
ASW0003b2f	0.191	24	5183f151e4bb210219025ac7.png	known
ASW0002eb8	0.294	44	5183f151e4bb21021901b4f4.png
ASW0001b4j	0.278	36	5183f151e4bb21021900ee93.png
ASW0005j54	0.266	50	5183f151e4bb21021903f028.png
ASW00006ka	0.262	36	5183f151e4bb21021900213a.png
ASW0009cff	0.235	50	5183f151e4bb21021906a72b.png
ASW0009c1f	0.228	49	5183f151e4bb21021906a533.png	double
ASW000253m	0.224	48	5183f151e4bb210219018652.png
ASW0003gj8	0.203	50	5183f151e4bb210219027674.png	double
Thanks

**Comment by anupreeta27** [comment]
Reasonably good - ASW0001b4j (i stand by my previous comment :smile: )
interesting double - ASW0003gj8
okish - ASW0005j54, ASW00006ka

chance coincidence? - ASW0009c1f - yellow lensed images are hardly ever seen 
strange placement of arc - chance coincidence - ASW000253m

**Comment by aprajita** [comment]
Hi Claude & Anu 

It's very good to get this list of possible interesting candidates. Although, I'm a bit confused, @anupreeta27 is the list of P<0.3 from stage 2, sources available somewhere - sorry if I've missed this.

The bulk of the missed known lenses were lost at stage 1 not stage 2. As most of the known lenses that made it into stage 2 got selected as candidates at stage 2, I think we can presume the bulk of the new lenses would be the same. So while there may be interesting sources missed in stage 2 at P<0.3, we should also investigate some of the Talk interesting subjects that were stage 1 rejections. 

We haven't really come up with a good plan how to harness the information in Talk so after the papers are done, we should discuss some kind of coherent plan of how to collect these targets from Talk. We made an attempt a while back asking for your favourite targets that weren't in our list, but we need to do something in a more systematic way.

Aprajita.

**Comment by cpadavis** [comment]
Hi All,

The specific objects that were mentioned here by @ccld are in stage 2 and
have P < 0.3. Here is a list of ZooIDs for known lenses missed in stage 2
that some people marked as containing a lens. (In my cluster algorithm, if
no users marked the object, then it won't be found. This cluster algorithm
is used to also denote the number of people who mark the object (as opposed
to some other place in the field).) The probabilities I use come from the
stage 2 offline directory checked in to the github:

ZooID mean_probability people_marking_object people_marking_field
people_looking_at_field ID
ASW0002nsh 8.974819e-13 6 9 49 5183f151e4bb21021901e4f1
ASW0007x7a 2.483268e-01 10 12 50 5183f151e4bb21021905a3d6
ASW0007qve 1.811387e-01 12 12 50 5183f151e4bb2102190583ca
ASW0006hoa 1.933380e-01 4 9 49 5183f151e4bb210219049efa
ASW0004l7l 2.440299e-01 7 9 50 5183f151e4bb210219034461
ASW0004p94 8.133099e-02 6 9 50 5183f151e4bb2102190358d8
ASW0005exg 2.757075e-01 10 12 50 5183f151e4bb21021903dad4
ASW00000k1 2.100528e-01 9 11 50 5183f151e4bb2102190002d1
ASW0003s8h 8.261008e-02 8 10 50 5183f151e4bb21021902b1b1
ASW0003of5 1.369771e-01 5 6 37 5183f151e4bb210219029e61
ASW0003f0o 1.542154e-01 8 8 50 5183f151e4bb210219026ec8
ASW0003pvf 2.278101e-01 5 12 50 5183f151e4bb21021902a5bb
ASW0005saz 2.044009e-01 7 9 50 5183f151e4bb210219041e8b
ASW0008cu1 2.518480e-01 6 10 49 5183f151e4bb21021905f2f9
ASW000506n 1.385119e-01 4 7 50 5183f151e4bb21021903902f

Cheers,

chris

**Comment by aprajita** [comment]
Hi Chris
Ah OK thanks, sorry I misunderstood.
Aprajita.

**Comment by ccld** [comment]
My last four known lenses with low P bringing a total number of nine "known" having P<0.3
zooid P Nclass image comment
ASW0003pvf	0.132	50	5183f151e4bb21021902a5bb.png
ASW0003f0o	0.117	50	5183f151e4bb210219026ec8.png
ASW000506n	0.027	50	5183f151e4bb21021903902f.png
ASW0002nsh	0.000	49	5183f151e4bb21021901e4f1.png

**Comment by anupreeta27** [comment]
let me know if there's anything or any reference i should give in paper 2 on this issue otherwise i consider this closed.
