### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by arfon** [drphilmarshall/SpaceWarps#125]
Heya, congrats on the paper - more comments from me in the coming days. One quick question, I notice you've picked [GPL](https://github.com/drphilmarshall/SpaceWarps/blob/master/LICENSE) as the license for the code in this project. I was wondering if that was a deliberate decision or whether you'd consider something more permissive.

Rather than regurgitate old works, I'll just like to @jakevdp's excellent piece on AstroBetter here:

- http://www.astrobetter.com/the-whys-and-hows-of-licensing-scientific-code/

**Comment by drphilmarshall** [comment]
Thanks @arfon. The GPL License choice was made in spring 2013 before I developed my own appreciation of MIT/BSD, and I never got round to fixing it. Im happy to change.

**Comment by arfon** [comment]
:zap: :rocket: :bow:

**Comment by jakevdp** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap:
