### ISSUE TITLE
Text looks fuzzy on some figures

### ISSUE THREAD

**Issue by arfon** [drphilmarshall/SpaceWarps#127]
This could be my tired old eyes but some of the figures don't look very sharp to me. As an example:

![screen shot 2015-04-14 at 9 41 40 pm](https://cloud.githubusercontent.com/assets/4483/7151402/22191452-e2ef-11e4-90a7-718ad2b8ebaf.png)

**Comment by arfon** [comment]
(Mean't to say this is the [sw-system](https://github.com/drphilmarshall/SpaceWarps/blob/master/doc/sw-system.pdf)) paper.

**Comment by cpadavis** [comment]
@drphilmarshall your figures turned out less blurry than these (which I made). Is there something I can do to make my figures, well, better? Is it just a matter of making them bigger?

**Comment by drphilmarshall** [comment]
Could be a couple of things going on. One is to set the dpi level in the
matplotlib figure to a highe rvalue (100 pr more). Another is to check that
the committed files are python-made PNGs and not images scraped from github
issue threads...

**Comment by drphilmarshall** [comment]
Hey @cpadavis if it's not just a simple remake that fixes the ROC curve plot fidelity, try something like

    fig, ax = plt.subplots(figsize=(10,8),dpi=200)

**Comment by cpadavis** [comment]
Remade figs 7, 8, and 12.

9-11 also look a little blurry. I think those are from the make_crowd_plots.py, and I think @drphilmarshall made those?

**Comment by drphilmarshall** [comment]
Hey @cpadavis, I got best results by switching to PDF format output in the end - see new versions of 8, 9, 10 and 13. Want to give this a try? You just change the name of the output file and `matplotlib` does the rest.

**Comment by anupreeta27** [comment]
i am using pdf format for all my figs. and i have no problems indeed.

**Comment by cpadavis** [comment]
done. I think all the figs are now much better looking :)

**Comment by drphilmarshall** [comment]
Thanks @cpadavis !
