### ISSUE TITLE
Paper2 footnotes Links to be checked 

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#129]
Paper 2
Footnotes
1- http://masterlens.astro.utah.edu : no anonymous browser view available
2- These numbers are estimated from http://terapix.iap.fr/cplt/table_syn_T0006 : page not found 
update http://terapix.iap.fr/cplt/T0007/doc/T0007-doc.html ? see footnote 8
3- "final T0007 release taken from the Terapix website for this work" refers to release 6: http://terapix.iap.fr/cplt/T0006-doc.pdf 
instead of 7 http://terapix.iap.fr/cplt/T0007/doc/T0007-doc.pdf see footnote 8
4- http://www.ita.uni-heidelberg.de/maturi/Public/arcs : page not found

**Comment by anupreeta27** [comment]
Thanks so much for checking these!!

1 - I was hoping that people would click on "The orphanlens project" tab on the left which is visible to anyone but I will use a more direct link
2 - looks like they've moved the original link. this used to work before.
3 - forgot to update
4 - latex typo fixed
 
Thanks again, I appreciate you checking these links. I've fixed all of them.
