### ISSUE TITLE
Paper 1: Typos

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#130]
see tiles cutouts size set in paper 2

abstract "430,000 overlapping 84 by 84 arcminute tiles"  to be 81.84 arcsec

in 3.1 "430,000 equal size, overlapping tiles, approximately 70 arcsec on a side."  to be 81.84 arcsec

**Comment by ccld** [comment]
§1 Inada et al. 2012; ?;?; ?),  
   (Quimby et al. 2014; ?)
§2.3.2 Figure ?? shows
§3.1 The CFHT Legacy Survey (CFHTLS, ?) covered 171 square
§6.1 p.15 the model of Simpson (????)
§REFERENCES Simpson, E. ????, XX. XXX. xx

>  fix question marks

**Comment by ccld** [comment]
§1 several of us (AV,CC,CM,EB,PM,TJ,LW) were active in an informal Galaxy Zoo gravitational lens search:
>
JW misspelling LW? 
who's TJ ?

**Comment by ccld** [comment]
Why such a mix of "color" and "colour" ?

**Comment by Capella05** [comment]
LW = Gumbosea (I think!)
TJ = Tommy J
I was never really that active on the forum thread.

**Comment by drphilmarshall** [comment]
Thanks @ccld this is most helpful. @Capella05 solved the initials list, I just replaced all the US color spellings (pardon!), and these are the missing references (for me to look up):

* [ ] SBAS
* [ ] SGAS
* [ ] CASSOWARY
* [ ] KellyEtal2014
* [ ] CFHTLS
* [ ] IBCC, in tex and bibtex, issued separately in #122

**Comment by ccld** [comment]
§6.1 p.15 the model of Simpson (????)
§REFERENCES Simpson, E. ????, XX. XXX. xx

http://arxiv.org/abs/1206.1831 Dynamic Bayesian Combination of Multiple Imperfect Classifiers 
Edwin Simpson, Stephen Roberts, Ioannis Psorakis, Arfon Smith

**Comment by ccld** [comment]
Figures appears in weird order: 6/8/7/10/9  ?

**Comment by aprajita** [comment]
LW is Layne Wright
TJ is Thomas Jennings
but they have not responded to opt-into the papers yet so don't appear on the author list
