### ISSUE TITLE
Paper 1 - 2.2.2. - Another possible revision to improve readability?

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#132]
I found the grammar and structure of this paragraph a bit odd (sorry!):

"At this point, the distribution of lens and source properties are quite realistic. At this point, we chose to make several cuts, to reject sims that were likely to be diﬃcult to spot. While this ensured the educational value of the sims when giving feedback, it meant that we should only expect to detect real lens candidates that also pass these cuts. Any real lenses candidates we ﬁnd with properties outside the ranges of the sims may in some sense be considered bonuses..."

Just my suggestion:

"At this point, the distribution of lens and source properties are quite realistic. We now chose to make cuts of the simulated lens pool, in order to reject sims that were likely to be diﬃcult to spot. While this ensured the educational value of the sims when feedback was given, it meant that we should only expect to detect real lens candidates that also pass these cuts. Any real lens candidates we ﬁnd with properties outside the ranges of the sims, may in some sense be considered bonuses…"

I am sure you can come up with something better :-) Also, feel free to tell me to stop providing feedback, if you think I am overstepping the mark!

**Comment by drphilmarshall** [comment]
No no, @Capella05, this is all good! Thank you very much for proof-reading, I adopted your improved text wholesale.
