### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#133]
Paper 2 
page 5   "deVaucoleur's"  >   de Vaucouleurs

**Comment by ccld** [comment]
Paper 2 
p.3 our bonafide lens sample > bona fide
p.5 We draw a Poisson deviate, > deviation
p.15 a value of the elongation stimator > estimator

**Comment by anupreeta27** [comment]
thanks. fixed!

**Comment by ccld** [comment]
Table 3: Sample of the SpaceWarps new lens candidates.
SW ID Name RA Dec zphot mi RA G ZooID P Comments

zphot(from CFHTLS data?),  G grade by expert, P probability by zooites
Column RA " > seems to be Einstein radius? (RE)

**Comment by anupreeta27** [comment]
done!
