### ISSUE TITLE
Paper 1: 6.3 - Increasing Capacity - typo

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#137]
" In Section 5.2 and Table 2, a rough picture emerged for the ***SpaceWarps crowd of it*** containing a few ..."

**Comment by Capella05** [comment]
Another one in the second paragraph:

" Greater exposure of the website to the public through mass media ***woudl*** help."

**Comment by drphilmarshall** [comment]
Thanks @Capella05!
