### ISSUE TITLE
Paper 2: 6.3- Measurements of properties of the lens and the lensed images

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#141]
Second paragraph.

Is there a link or reference that is missing?

" For the RingFinder sample, the arcs are detected in the scaled diﬀerence image of g and i bands from which the lensing galaxy is subtracted (Gavazzi et al. 2014, for details, ***see***). "

**Comment by anupreeta27** [comment]
nope. words should be interchanged  -- for details see Gavazzi et al.
thanks !
