### ISSUE TITLE
Paper 2: 3.1.1 Galaxy-scale lenses - a question.

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#142]
This is more of a question out of curiosity than an issue :-)

From Paper 2:

"We begin by considering all elliptical galaxies at z < 1 in our parent CFHTLS catalog (Gavazzi et al. 2014) as potential lens candidates for the simulated sample. To avoid using a known lens galaxy for our simulation purpose, we exclude all those galaxies whose positions match with the lensing galaxies from the SARCS samples within 2 arcsec."

There are a lot of examples in Talk, of sims overlapping known lens candidates.

For example:
ASW0005nx7
ASW0002nsp
ASW0004aju

It became a bit of a game looking for them under the sims - was this intentional? or were the galaxies incorrectly selected to be a host for sims?

**Comment by anupreeta27** [comment]
Thanks for asking. I intend to write a couple of sentences on this before you see the final version. 
Anyway, fyi : we tried to remove the ones that matched within 2 arcsec. but realized later that our position measurements of the centers were not accurate enough or sometimes didn't correspond to the center of a galaxy. Thus, some lensing galaxies were not excluded and happened to have sims. I will leave this open until I add a short para on this in the paper.
