### ISSUE TITLE
Section 2.2.2 comments

### ISSUE THREAD

**Issue by chrislintott** [drphilmarshall/SpaceWarps#144]
You have, in section 2.2.2 a description of how you should expect only lenses that are similar to those in the training set to be found by the system; you do mention that those lying outside the ranges of the sims are 'bonuses', but I think we should be stronger here. AV made the point in her Kavli talk last week that a key advantage of humans is their ability to go beyond their training - e.g. discovering the (red) SpaceWarps lens when the training set and the field guide were all (blue). Happy to suggest text if you like (assign me the issue) but thought I should check first.

**Comment by drphilmarshall** [comment]
You're right, we should make more of this. The key figure is in Paper II
though (the blue rectangles) - so in Paper I I was just trying to
anticipate that. Please do suggest some additional text for either paper!
