### ISSUE TITLE
Repetitive text in 2.2.3 and 2.3.1

### ISSUE THREAD

**Issue by chrislintott** [drphilmarshall/SpaceWarps#145]
Both of these sections have a description of how duds were selected; you should consider avoiding this repetition.

**Comment by drphilmarshall** [comment]
While fixing this issue I wrote the following (line 520):

    The \StageTwo duds were selected from a small random subset of the
\StageOne candidates (i.e., the \StageTwo
    duds were expert-defined \StageOne false positive detections)

Is this correct, @aprajita @anupreeta27? Just checking.
