### ISSUE TITLE
Paper 1 figure files are too big for arxiv

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#154]
We need to reduce the size of the paper 1 figures by a factor of 10 before arxiv will accept it.

From @anupreeta27 :

* [ ] "It looks like all the individual figs made in Paper I have very large dpi making each fig >100K. Since its not easy for me to regenerate all figs, I suggest you do this with the default dpi value in the matplotlibrc file for savefig.dpi. This is certainly good for PDFs that I made for paper 2." @cpadavis, can you remake your figures with 100dpi PDF if they are not already, please? I will do the same.

* [x] "Some of your pngs are also very large. The screen-grab png is 1Mb - for comparison- this is equivalent to the size of ALL of the figs from Paper 2.  Please reduce the png sizes and possibly convert them to PDF. Also, you have several loose pngs (each of ~400KB) in a single fig (e.g. fig.2,3,13) - this increases the fig size by several factors - for comparison - 3 such pngs combined into a single pdf gives me ~300KB (see fig 1 of Paper 2). You can convert this with [the same script I used](https://github.com/drphilmarshall/SpaceWarps/blob/master/doc/scripts/simsfig.py) to read an array of pngs and combine it to a single pdf." I'll try compressing the pngs into jpg, etc. I have played this game before...

* [ ] "A suggested reasonable size for a fig on arxiv is 50KB and most of my figs are under 20KB except when showing CFHTLS images. Since I don't know any other specific upper limits, please make sure that the folder sw-system-figs is not too large than 1Mb because this definitely worked for paper 2."
  
* [ ] "One more thing  - ":" are not allowed in filenames. I had fixed this locally during submission. Could you please rename some of your pngs by replacing ":" with "_" ?"

**Comment by drphilmarshall** [comment]
Stand down, @cpadavis : changing the `dpi` setting does not reduce the filesize. I am resorting to JPG compression and then conversion back to "_compressed.pdf". This is good enough for arxiv I think. As soon as we have submitted we can put the latex back to point at the uncompressed figures.

**Comment by chrislintott** [comment]
Worth linking from arXiv to a full res version on github, perhaps?

**Comment by drphilmarshall** [comment]
Yes, good idea Chris. I'll merge this off into an 'arxiv' branch, and put the latex back to pointing at the full res plots. The images can stay small I think.

**Comment by drphilmarshall** [comment]
`21 pages, 13 figures. A full resolution version of the paper can be downloaded from https://github.com/drphilmarshall/SpaceWarps/blob/master/doc/sw-system.pdf . Comments welcome at https://github.com/drphilmarshall/SpaceWarps/issues`

**Comment by anupreeta27** [comment]
@drphilmarshall you can scale the png to a smaller size using gimp or convert

**Comment by anupreeta27** [comment]
@drphilmarshall please delete images that are not being used from the arxiv branch, i could then use files from this branch.
