### ISSUE TITLE
Paper 2 - Introduction - Mistake raised on GZ Talk by 'mlplek'

### ISSUE THREAD

**Issue by Capella05** [drphilmarshall/SpaceWarps#156]
From this thread: [Recent GZ submissions to arXiv](http://talk.galaxyzoo.org/#/boards/BGZ0000001/discussions/DGZ0000zyi?page=2&comment_id=553901241c59aa38920007de)

Quote taken from thread posted by mlpek below

>New Space Warps paper on arxiv 23 April 2015:
>More, A. et al. 2015: "Space Warps II. New Gravitational Lens Candidates from the CFHTLS Discovered through Citizen Science."

>From the intro:

>>Galaxy Zoo was the first citizen science project in astronomy...

>Seriously?? That's one of the more absurdly ahistorical claims I've read recently.

He is technically correct. I have replied in the thread saying it is most likely a typo and that if 'that' was used instead of 'and', the sentence would make sense.

I will leave it up to you to decide what to do.

**Comment by anupreeta27** [comment]
@Capella05  
I certainly didn't mean to say that this is the first ever in astronomy - however, GZ is one of the first ones to have become successful and popular, and inspired many astronomers incl. myself to work in this direction.  

I do want to say something about GZ and it being one of the first ones to make it so popular but someone more knowledgeable could help me phrase this more accurately. @chrislintott - any suggestions?
