### ISSUE TITLE
Time-variable skill?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#157]
A theme that came up in our CFHTLS papers was this very simplistic assumption of time-constant skill (AKA "talent") that the SWAP agents make. An interesting test we could do as part of the eSWAP analysis could be to experiment with estimating PD and PL via a boxcar average over a moving window of N classifications, for various values of N. I think this could be an easy extension to the SWAP code, what do you think, @cpadavis?

**Comment by surhudm** [comment]
This sounds like a good idea, but does it mean we ignore the first few
classifications a user makes? This will cut a large number of
classifications. We need to keep the window N large enough to reduce noise
in the estimate of pl and pd.

**Comment by cpadavis** [comment]
Both the online and offline systems already downweight the first few classifications a user makes. I am interested i how PL and PD change with time (more in the sense of finding how big a window it would take for PD and PL to settle) and would be _very_ surprised if the PL and PDs really do vary with time (implying that our model of a fixed PL and PD is incorrect).

It should be easy to examine since we keep track of all the training evaluations already in annotation_history.

**Comment by surhudm** [comment]
I guess I do not fully understand offline analysis. I was under the
impression, that you were fixing the user's confusion matrix at the end of
the survey to be the matrix to update the probabilities of the subject
image. How does that down weight the first few classifications?

**Comment by cpadavis** [comment]
I should be more precise: it doesn't down weight the first few classifications, but it does smooth out agents who make only a few classifications such that your 'effective number' of classifications is less than the true number you make. Basically the smoothing factor helps account for the case when a user never sees a training lens or dud.

This can matter if you are using the offline analysis but only a smallish window of classifications.

Oooo I just looked at the code. We literally ignore the first couple measurements for test subject probabilities, but NOT for the PLs and PDs. My bad!

So for offline the PL and PD updating step looks like this:

    def heard_many_times(self, probabilities, classifications, laplace_smoothing=1.):
        # unlike the equivalent function in subject, this one does not need to
        # reference self.heard
        # classifications are assumed to be 0 (NOT) or 1 (LENS)
        # when in supervised mode, the probabilities are also 0 or 1
        probability_sum = np.sum(probabilities)
        probability_num = len(probabilities)
        classification_probability_sum = np.dot(classifications, probabilities)
        classification_sum = np.sum(classifications)
        self.PL = (laplace_smoothing + classification_probability_sum) / (2 * laplace_smoothing + probability_sum)
        self.PD = (laplace_smoothing + probability_num - classification_sum - probability_sum + classification_probability_sum) / (2 * laplace_smoothing + probability_num - probability_sum)

where laplace_smoothing is set to 1 here

**Comment by drphilmarshall** [comment]
No, we'd use all classifications until N+1 had been made, and from then on the most recent N. I am interested to see how the ROC curves change with N.

**Comment by drphilmarshall** [comment]
OK: we are going to punt this topic out of the eSWAP paper on the grounds that the right comparison to do would be eSWAP versus IBCC (which does include a model for time-variable skill). Such a comparison could well be done by someone at the Zooniverse in the next couple of years once both algorithms are implemented in the Panoptes system.
