### ISSUE TITLE
Paper II- Table 3 - candidates on overlapping frames

### ISSUE THREAD

**Issue by ccld** [drphilmarshall/SpaceWarps#159]
SW29 from frame  ASW0002p8y with P = 0.439 was better identified in frame ASW0002o2o P=0.561

SW25 from ASW0005ma2 was in blog /2013/08/15/x-marks-the-spot-new-gravitational-lens-candidates-from-space-warps/  as ASW0005mp6. I wonder why this later frame seems absent in stage 2?

**Comment by anupreeta27** [comment]
@ccld 
re. SW29 - that's fine, we are just reporting any one ID in the table, during visual inspection, both those images are being considered.

re. SW25 - its surprising, i can't find ASW0005mp6 anywhere in the stage 1 catalogs. 
@drphilmarshall - do you know why ASW0005mp6 isn't in stage 1 catalogs now ?

**Comment by drphilmarshall** [comment]
On Tue, May 5, 2015 at 10:51 AM, anupreeta27 <notifications@github.com>
wrote:

> ASW0005mp6


Maybe ASW0005mp6 was flagged in Talk but not classified with high P, even
though the same candidate in a different subject did make it across the
detection threshold...
