### ISSUE TITLE
"Known Lenses" not being classified?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#202]
We write in paper 2 section 7.3.1:

"Surprisingly, most of the lenses in the known sample have few classifications (Nclass<10) which includes both the detected and missed lenses."

But then we say:

"Overall, we do not find any correlation for the detected and the missed sample with Nclass."

I think these statements need clarifying in order to be consistent. Correlation between what and what?

Could people be going straight to Talk rather than marking the image, when they see a known lens? This could be tested with a future Talk comment text analysis.

**Comment by anupreeta27** [comment]
stage 1 report says mean classn/test subject is 8.4. so, i don't think KLs are special in any way.
My "surprisingly ..few classfn" was probably either wrt to Nclass_max=50 or for the fact, that this was similar for both detected and missed lenses. i was expecting that probably missed lenses would have fewer Nclass than the detected ones but this was not the case.

**Comment by aprajita** [comment]
so will you edit the text in that section accordingly then?
hope you manage to get some sleep before our telecon…

**Comment by ccld** [comment]
What was your take on known lenses overlapped by training sims?

**Comment by drphilmarshall** [comment]
It was good that we put those images into the system without sims as well!
The false negative effect we are discussing here is not affected by the sim
placement, I think.

**Comment by ccld** [comment]
I can't find images without sims  of those overlapping known lenses
#sim overlapping #known
SA11	ASW00015xe 
SA52	ASW0004aju
SA68	ASW0000joc
SA86	ASW0006842
SA89	ASW0006eoq
SA115	ASW0007en2
SA127	ASW00093k7
SL2SJ140614+520252 ASW0005nx7

and for sim & known in same frame SL2S J084847-035103 ASW0004wuj

Could it yield an effect on known classification?

**Comment by anupreeta27** [comment]
@ccld  not to worry, they are there. we are not missing any lenses because of this. all subjects without the sims were added and they all are processed similar to the other subjects  
just fyi e.g. SA11 ASW00099dy, SA52 ASW0009ad3, SA68 ASW0009b7u and so on..
