### ISSUE TITLE
Consistency paper 1 & paper 2

### ISSUE THREAD

**Issue by aprajita** [drphilmarshall/SpaceWarps#207]
Anu settled on using 'volunteers' to refer to the citizens in paper2, whereas paper 1 uses users. i personally think either is fine. checking whether @drphilmarshall wants me to replace users with volunteers while I am editing paper 1

**Comment by anupreeta27** [comment]
some time back we decided to use volunteers, citizens or citizen scientists instead of users.

**Comment by aprajita** [comment]
yes i remember that we agreed on that, but it's propagated in paper 1, in my branch i've changed most users to volunteers or citizens, but have kept in a few occurrences for things like super-user etc..

**Comment by anupreeta27** [comment]
@drphilmarshall  when describing the traj. plots, should we use the term "kick" in paper I as well instead of "step" ?

**Comment by drphilmarshall** [comment]
Good idea. I'll look at this now.

**Comment by anupreeta27** [comment]
@drphilmarshall thanks. fyi, i am doing some minor edits on paper 1 in a separate branch. will send you a pull request soonish.

**Comment by anupreeta27** [comment]
@drphilmarshall  many of the figs. still have labels "Stage 1" and "Stage 2" - not consistent with the terms in the text.
