### ISSUE TITLE
Anu's final Paper 1 queries

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#210]
From skype earlier:

* 3381 candidates, abstract and Table 2
* 'Stage I' not 1
* Candidate numbers in speed section
* Put purity in context - how good is 30%?
* Offline ignores 1st N classifications - what is N?
* Figures in correct order?
* Remove information column from Table 2?

**Comment by cpadavis** [comment]
howdy from michigan,

offline takes all appropriate classifications, but smooths the estimates of
PL and PD with laplace smoothing (basically add one to numerator and two to
the denominator when computing the sums. This means that if a user makes
very few classifications then it washes out the content of those
classifications as far as evaluating PL and PD).

I am taking this info from the code, so it should supersede any mistakes I
made earlier :)

---chris

**Comment by drphilmarshall** [comment]
Thanks Chris!
