### ISSUE TITLE
Paper 2 Referee Report

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#217]
Reviewer's Comments:

This work merits publication after some minor revisions.
Following the order of the text, my comments (on both form and content) are :

* [ ] In the abstract, I would replace "albeit at the cost of a higher false positive rates" by "albeit at the cost of a lower purity", the purity is a quantity well known by the astronomers and I think it makes things clearer here (especially for an abstract).

* [ ] The short Section 4 should become the 4th subsection of Section 3 with slight changes in the titles, like :
          3. Training Sample
                  3.1.  Methodology to simulate lenses
                  3.2. Simulated lens sample and catalog description [no change]
                  3.3. Limitation of the simulated lens sample [no change]
                  3.4. Duds and impostors
and by adding a word about duds at the end of the introduction of Section 3.

* [ ] There is sometimes a confusion between real lensing galaxies and real galaxies chosen to be lensing galaxies in the training set of simulations. For example, in the last paragraph before subsubsection 3.1.2., in the sentence "the simulated image is added to the real CFHTLS image centered on the lensing galaxy", the authors should write 'lensing galaxy' between quotes or rephrase it : "..centered on the galaxy chosen to act as a lens". The same remarks applies to other occurrences in the same paragraph (and maybe others in the rest of the text).

* [ ] The caption of Figure 2 should be completed : "Einsten radius and total magnification distributions..."

* [ ] Last paragraph before subsection 3.3, first sentence, I would precise : "We produce catalogs with lens and source properties for each of the three types of SIMULATED lenses."

* [ ] There is sometimes a confusion between the (evolving) posterior probability after each classification and the final posterior probability after stage 2, and both are noted P (even if I understand that somehow this is the same quantity). Maybe the authors could note the final posterior Pf and/or be more specific in the text. For example, in the caption of Figure 4, or, in subsection 5, paragraph 3, line 5 : "Each subject, after Stage 2, has a FINAL posterior probability P".

* [ ] In Figure 4, there should be a better color contrast between the new candidates and the known candidates to make the results more readable.

* [ ] Page 9, subsection 5, 4 lines before the end of paragraph 2, I would precise "In stage 1, ..." before "...those images which cross these threshold values are 'retired'"

* [ ] Maybe the authors should re-explain (Paper I) quickly at this stage of the article (3rd paragraph of subsection 5) that the stage 1 favors completeness while the stage 2 favors purity of the final sample.

* [ ] Subsection 6.2, paragraph 3, penultimate sentence, I would precise : "...the atypical color and structure of the LENS galaxy"

* [ ] At the end of subsection 6.4., as well as in the conclusion, the authors quickly deal with the subject of the deflector subtraction. I would like them to make clearer in their article that this is not a trivial issue in the detection of galaxy-scale lenses, and that solutions are being actively sought for a better subtraction of this foreground light.

* [ ] There is sometimes a confusion between the various subsamples considered in the article. For example, in Subsection 6.5, paragraph 2, lines 4-5, it is hard to distinguish in the text if the "known" samples considered refer to confirmed lenses or the whole candidates.

* [ ] In subsection 6.5, describing Figure 7, could the authors say one word about the few points at lower image separation which are not consistent with the "total" profile?

* [ ] There is some overlap between Section 6 and Section 7, even if the developments are interesting. But maybe Section 7 should be somehow shortened for clarity?

* [ ] The title of subsubsection 7.3.2. "Blind lens search" seems a bit too general and maybe not relevant. It should be replaced by something more specific like "Lens positions in the image cutouts".

* [ ] In Figure 11 and its description in the text (subsubsection 7.3.3, paragraphs 4 and 5), the distinction between the red and green curves is unclear, especially for what concerns the detected lenses. There should be a word about it in the caption of the figure too.

* [ ] Subsubsection 7.3.3, paragraph 7, I think there is a mistake in "i) The ratio of large positive kicks to small positive kicks for the detected sample is higher than in the missed sample"... I think the authors meant "negative" instead of the second "positive"?!

* [ ] Last paragraph before Section 8, I would again replace "increase the rate of false positives" by "decrease the purity".

* [ ] The authors could mention EUCLID with the other future surveys in their conclusion.

**Comment by anupreeta27** [comment]
all done!

**Comment by drphilmarshall** [comment]
Hooray! :-)
