### ISSUE TITLE
Paper 1: Better color contrast on trajectory plots

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#219]
Edit SWAP to make red and blue points bigger, red and blue trajectories thicker and less alpha'd, red and blue histograms in the foreground with alpha=1.

**Comment by drphilmarshall** [comment]
@cpadavis Do you have a mongodb running? If so, could you please do a quick online CFHTLS Stage1 SWAP run please? I've updated the trajectory plot code in `subject.py` and `collection.py` to improve the color contrast, but now we need some plots to choose from. Maybe set `N_per_batch` to 100,000 and just wait a few batches? Thanks!

**Comment by cpadavis** [comment]
@drphilmarshall I have made 100 sample trajectories and put them in a big pdf here:

https://www.dropbox.com/s/yf3gc1n287qm0ds/merged.pdf?dl=0

(this'll probably go away once we close this issue)

Which one do you think looks best? I'll find that one and put that as the new trajectory figure

**Comment by aprajita** [comment]
Hi @cpadavis, I think page 14 looks good, but leave it up to @drphilmarshall 

some weird things going on with some of the sims e.g. page 3, 16...

**Comment by drphilmarshall** [comment]
I think I like 39 a bit better, because it has more red and blue lines on
it (which the referee wanted to see. Can you check this one in, make sure
the latex compiles and close this out, please? Thanks Chris!

**Comment by cpadavis** [comment]
done
