### ISSUE TITLE
Paper 1: Figure 6 clarity/readability

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#220]
Our referee says:

"Page 12, Figure 6, the different linestyles should be replaced by different colors to make the whole plots more readable, and to be able to distinguish the 4 "stars" corresponding to a lens probability threshold of 0.95 in each case."

Can you take care of this please, @cpadavis ? I think we can argue down the request for different colors (the different linestyles are enough) but the points need fixing. The legend will need to show which point style goes with each line... If you decide to experiment with color, can you choose 4 shades of blue and orange, please? Thanks!

**Comment by cpadavis** [comment]
done. let me know if you want the marker sizes bigger or smaller (there's a tradeoff between viewability on the figure and on the legend)

**Comment by drphilmarshall** [comment]
Looks good to me - thanks @cpadavis!
