### ISSUE TITLE
Paper 1 referee response: very minor revision to figure captions, acknowledgments

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#222]
Fix captions, as suggested by the referee below - and add a thank-you note to them in the acknowledgments.

>Figure 5 and figure 6 are both much more readable in the revised version of the paper, nevertheless :
>
> - In figure 5, in the bottom panel, one does not distinguish anymore the black histogram of the test subjects at posterior probability 1, which seem quite important as they "will help make up the candidate sample" as said in the text. I guess the "test subjects", "sims" and "duds" are now plotted in that order so that the blue histogram hides the black one, but I just wanted to point that out.
>
> - In figure 6, for stage 1, one does not distinguish the 'little blue circle' corresponding to a lens probability threshold of 0.95 in the case of the online analysis, which seems again important since the stage 2 sample is defined using the results of this analysis. I guess the circle is overlapped by the 'little blue square' but maybe it should at least be said in the caption of the figure.

**Comment by drphilmarshall** [comment]
Add Fritz to list of acknowledgments in lieu of paper 2 thanks. ( #223 )

**Comment by aprajita** [comment]
i think anyway paper 1 is more appropriate for fritz, as well as zooniverse team we need to thank if anyone has been missed.

**Comment by drphilmarshall** [comment]
Ok, thanks! Resubmitting now.

**Comment by drphilmarshall** [comment]
Done! :-)
