### ISSUE TITLE
Paper 2 referee response: colors in Fig 11, acknowledgments

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#223]
Maybe we should re-make this figure?

> I still find a bit confusing the way colors are used in the left panel of Figure 11 : I understand each case but I think 2 different couples or shades of colors should be used, since the couple {red, green} does not really represent the 'same distinction' for the missed lenses on the one hand and for the detected lenses on the other hand.

Then, in the paper itself we should add a thank you to the referee, after any other thank you's we have. It woudl be good to mention people who helped out in Talk, in particular Alexander Fritz (who was active at the start but didn't make the author list cut). Other Zooniverse people who advised on the app implemntation and analysis would also be good (Borden, Carstenson etc).

**Comment by aprajita** [comment]
@anupreeta27 has already made the paper 2 changes and it has been accepted.
so any additions should be added to paper 1

**Comment by drphilmarshall** [comment]
Good, OK - I'll do that. @anupreeta27 can you `git push`, please? Thanks!

**Comment by anupreeta27** [comment]
ok done!
