### ISSUE TITLE
sims - differences in training vs. experienced phase

### ISSUE THREAD

**Issue by anupreeta27** [drphilmarshall/SpaceWarps#24]
Question:
should we have created two kinds of sims in terms of difficulty levels -
1. easy-to-identify sims for training purpose (bright enough, simple configurations, etc.?) for the training phase
2. more realistic (low surface brightness, complex lens configurations) sims for experienced  phase ?

Another way to see this is: Since the sims might be a relatively simpler lens sample, could the "experienced or super users" be good at identifying sims but not so great in identifying "real" lenses or rejecting false positives (FP)?

Investigate: 
One way to investigate this is to check how well the experienced or super users are performing on the known lens sample and on the (now) known FP sample. It would make sense to do this on stage 1 because at least, at that point, we had not provided  any FP sample.

**Comment by drphilmarshall** [comment]
I *think* this has been superceded by later issues....
