### ISSUE TITLE
Ask LensHunters if they've seen any lensed quasars, or other exotica?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#47]
Context is, we're writing papers and want to catch things before they fall through the cracks.

**Comment by ccld** [comment]
Hi all,
After some review, I collected some lensed quasars candidates to my opinion which seem to have been missed or not graded:

http://talk.spacewarps.org/#/collections/CSWS001xtk

ASW0000wqt
ASW00019n9
ASW0008qab
ASW0001sbe
ASW00032zn

May be not too late for further analysis (said in Aprajita's preparation)
Cheers
Claude

**Comment by aprajita** [comment]
Thanks very much Claude, I'll take a look!!

Aprajita.
