### ISSUE TITLE
Make "standard" HumVI PNGs of all DES test images

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#89]
Start with single set of scales/pars and see what they look like.

**Comment by drphilmarshall** [comment]
Closing this, investigation of depth-dependent settings is a separate issue.

**Comment by kapadia** [comment]
@drphilmarshall do you have a document describing the HumVI representation. I'd like to re-read it, and pass it along to a colleague.

**Comment by drphilmarshall** [comment]
Thanks Amit - I just added some explanatory HumVI text to our SW system
paper, and pointed the [HumVI README](
https://github.com/drphilmarshall/HumVI/blob/master/README.md) at it, hope
this helps!

**Comment by kapadia** [comment]
This is perfect. Thanks @drphilmarshall! Also, thanks for pointing to the draft paper :smile:  in the doc.
