### ISSUE TITLE
What if we had done Stage 2 with only high skill volunteers?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#90]
We need to know this in order to design dynamic stage 2 for the next (DES) project.
Let's bin the CFHTLS stage 2 agents by final skill, and for each group, ask how well they would have done at the refinement stage classification. @cpadavis your idea is simply to make ROC curves for the stage 2 offline analysis only using each group's agents, and compress these into the area under the curve as a measure of classification performance. (Actually lets use the Informedness = 2AUC-1) Looking forward to seeing I vs skill! :-)

Nb. This issue is describing "test 2" from issue #68...

**Comment by cpadavis** [comment]
Doing the above analysis this is what we obtain (first informedness column is from using the simulated lenses + duds to evaluate performance, and the second from using real lenses + duds to evaluate performance.)

Skill        	Informedness 
-------------	-------------
0.000 - 0.005 	0.227	0.128
0.005 - 0.010 	0.275	0.264
0.010 - 0.030 	0.568	0.379
0.030 - 0.080 	0.691	0.720
0.080 - 0.200 	0.863	0.797
0.200 - 1.000 	0.981	0.982
effort	 	0.955	0.963
all	 	0.976	0.979
Note: second and third skill bins do not see all lenses

The 'effort' group are the users who classified at least 300 test images.

I also attach the ROC curves using simulated and real lenses:

![screenshot 2015-02-17 17 30 21](https://cloud.githubusercontent.com/assets/1781988/6240955/b92aa4f6-b6ca-11e4-90af-d67cf61c3eb9.png)
![screenshot 2015-02-17 17 30 27](https://cloud.githubusercontent.com/assets/1781988/6240956/b92b096e-b6ca-11e4-80ac-5a2d6beab4e0.png)

The conclusion I draw is that while a lot of classification power comes from the high skill users, the lower skill users don't drag the results down that much. (And of course a tradeoff that is invisible to these data are the total number of objects classified.) We would have seen marginal improvements using only high skill volunteers.

**Comment by drphilmarshall** [comment]
Thanks Chris!  I agree with your conclusion, it's really interesting how
close "all" and "skill > 0.2" are! That means doing stage 2 with everyone
is "safe". If we wanted to do stage 2 dynamically though, for efficiency, I
guess admittance via skill rather than effort has some small benefit, but
as you've shown, not much. If we had only asked the high-effort volunteers
to do stage 2, our results would have been slightly worse (either less pure
or more incomplete or both).

Just to be clear, here: does skill refer to stage 2 skill current skill,
stage 2 final skill or stage 1 skill? I guess its the latter that is most
relevant for dynamic stage 2 design.

**Comment by cpadavis** [comment]
Just to be clear: this is stage 2 final skill. See issue #73 for selections based on end of stage 1 skill.
