### ISSUE TITLE
What is the contribution rate (with time)?

### ISSUE THREAD

**Issue by cpadavis** [drphilmarshall/SpaceWarps#95]
A plot with these two lines would be nice:

1. Classification rate vs time
2. Contribution rate vs time

note: gonna have to add an 'at_time' type parameter to the annotation / test / training histories of subjects and agents respectively

**Comment by cpadavis** [comment]
Work in progress:

I added the at_time parameter to both the agent and subject histories. I haven't yet made graphs of the rates of contributions, but here are some cumulative plots which make for an interesting relative comparison.

On the x axis I plot the fraction of completion of the stage. On the y axis I plot the cumulative sum of either classifications or contributions and normalize to 1.0. That is, with each classification a user either +1 to total classifications, or +skill to contribution.

![download](https://cloud.githubusercontent.com/assets/1781988/6241037/e35eefe2-b6cb-11e4-9709-fae1630da525.png)

The most interesting comparison to be made with the cumulative statistics (since that graph isn't particularly illuminating) is to compare between classifications and contributions -- I take above graph and plot stage_n_contribution - stage_n_classifications. This graph shows which feature 'fills up faster', so to speak.

![download 1](https://cloud.githubusercontent.com/assets/1781988/6241057/27a04ba6-b6cc-11e4-939c-151b06afab1c.png)

Stage 1 behaves as you expect: the classifications fill up faster than the contributions, because a lot of low skill users initially classify but at the end higher skill users are all that remain.

Stage 2 behaves differently: the skill contributions fill up faster than the classifications. Did we keep high skill users from stage 1 who then got tired over time?


on the todo list is making contribution and classification rate plots.

**Comment by drphilmarshall** [comment]
"Did we keep high skill users from stage 1 who then got tired over time?"
Looks like it, doesn't it? We probably had a steady trickle of new stage 2
volunteers arrive during the stage, whose classification rate outpaced
their information contribution rate.

BTW Can you switch the color schemes (stage 1 = blue) please? And also the
y axis on the diff plot should say what positive means. TBH I think the
first plot is the most informative: to a good approximation, the
contribution rate tracked the classification rate, and the initial spike
was as informative as the coasting phase in the summer. Interesting!

**Comment by cpadavis** [comment]
Here is the cumsum graph with the right colors:

![cumsums](https://cloud.githubusercontent.com/assets/1781988/6377862/1d1a5c42-bcdc-11e4-9d38-a1a2563e4ef9.png)

Next I look at the classification rates, average skill, and contribution rates. First I show a histogram of the skill of users in stage 1 vs stage 2. Stage 2 users are not less skilled than stage 1 (and actually they are probably _more_ skilled!). Instead, stage 2 users faced much harder simulated lenses and duds:

![skill_hist](https://cloud.githubusercontent.com/assets/1781988/6377878/3b07776c-bcdc-11e4-9772-6125ef37b32b.png)

Now I show the classification rates as a function of project time. I smoothed the rates over 24 hours and 5 hours for stage 1 and 2 respectively, but I did not normalize them to the total number of classifications:

![cr_1](https://cloud.githubusercontent.com/assets/1781988/6377911/81ddf67a-bcdc-11e4-9033-bba34fa54eff.png)
![cr_2](https://cloud.githubusercontent.com/assets/1781988/6377912/81f68ce4-bcdc-11e4-823b-a725bd5782e1.png)

Now I show them together normalized to survey time and total number of classifications:
![cr_both](https://cloud.githubusercontent.com/assets/1781988/6378693/d84769b0-bce1-11e4-8f11-2c322fff213b.png)
So the majority of classifications are done relatively early on. (Though 1000 hours ~ 40 days, so unless there was a very long campaign to promote spacewarps, it seems unlikely to just be initial advertising.) There is a much steeper descent with stage 1 than with stage 2, which seems to level off relatively quickly.


How is the average skill of a user changing with time? I show that and the standard deviation both as a function of time, again smoothed over the 24/5 hour scale:

![average_skill_1](https://cloud.githubusercontent.com/assets/1781988/6378778/60af902a-bce2-11e4-8665-c4fcd3ef9425.png)
![average_skill_2](https://cloud.githubusercontent.com/assets/1781988/6378777/600eb95c-bce2-11e4-9753-2aaa221e95f5.png)
![skill_std_1](https://cloud.githubusercontent.com/assets/1781988/6378880/0f1f8e76-bce3-11e4-882c-8adf67246e04.png)
![skill_std_2](https://cloud.githubusercontent.com/assets/1781988/6378885/114e8706-bce3-11e4-8b95-370279df4ba4.png)


My interpretation is this: stage 2 users largely came in pre-formed, as the average skill (and its std) are roughly constant over the survey. Meanwhile, stage 1 users got better with time, though eventually the longterm users got bored and left.

The contribution rate is just the classification rate weighted by the average skill:
![con_1](https://cloud.githubusercontent.com/assets/1781988/6378888/15658330-bce3-11e4-849b-9e34f119363f.png)
![con_2](https://cloud.githubusercontent.com/assets/1781988/6378890/175fce3e-bce3-11e4-8044-bd1b72756e80.png)
![con_both](https://cloud.githubusercontent.com/assets/1781988/6378891/1971d2d0-bce3-11e4-8cf9-8195a246946a.png)


So maybe a good model for the time variations is this: there is a stream of new users encountering spacewarps. That stream starts off big (initial advertising) and then falls off to some constant level (users just looking for new zooniverse projects). Users stick around for some period of time, and as they stick around they actually do get better, or the ones who are better are more likely to stick around. Then in stage 1 we had a very large influx of folks, most of whom quickly left. Eventually mostly high skilled users remained, though they too left. In stage 2 there was probably less fanfare and you reclaimed many of those high skill users from stage 1, so all these effects were now less dramatic in skill.

**Comment by drphilmarshall** [comment]
Good! Figure and text now included in paper 1, via [this commit](https://github.com/drphilmarshall/SpaceWarps/commit/c26dd1bff8b1763d85b255e162ae0d4a5ba4a57f)
