### ISSUE TITLE
Address Aprajita's comments

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/SpaceWarps#96]

**Comment by drphilmarshall** [comment]
OK, I've gone through all your comments, @aprajita, see what you think. My false negative trajectory interpretation was just wrong, I checked the code and we did keep detections at their p > pmax probabilities, so they could not cross back over the threshold. (We then just left them in the system to delight people!). So I fixed that text.  I'm going to see what @anupreeta27 said in her comments about the level of detailed analysis we need on the causes of the false negatives/false positives, but my feeling is we do not need more depth than we already have. I'm going to close this one out, and will reopen something specific if I think we need it!

**Comment by aprajita** [comment]
OK, @drphilmarshall, there was a question i had about one of the user stats being used, can we talk about that later?

**Comment by drphilmarshall** [comment]
Sure - I think it was the information: that's something else I was going to
see what Anu said.
