### ISSUE TITLE
Is our PL the right PL?

### ISSUE THREAD

**Issue by cpadavis** [drphilmarshall/SpaceWarps#99]
We use simulations to train our agents, but we want our agents to find real live lenses, not simulated lenses. Additionally, the simulated lenses are often offensively obvious (at least in stage 1).

I'm going to ask and attempt to answer a question here: say we trained our users only on the known lenses (either online or offline methods). What PL would they have obtained? I can then make plots of PD as a cross check on my code: the PDs should not change at all. In fact, we expect a 1:1 between the PD and online/offline for stage1/stage2.

**Comment by cpadavis** [comment]
Here are the results. I use the same hyper parameters as we use in the real data. I also only selected agents who had classified at least one of the known lenses, and I only took their classifications for the duds and known lenses. This leads to some unfortunate peaks because of the 'skepticism' and laplace smoothing.

Here is stage 1:

PL's
![download 2](https://cloud.githubusercontent.com/assets/1781988/6241155/7aae9068-b6cd-11e4-9cf5-4f9332a019ef.png)

PD's
![download 3](https://cloud.githubusercontent.com/assets/1781988/6241156/7dfb094a-b6cd-11e4-945f-99cbb5117254.png)


and here is stage 2:

PL's
![download 4](https://cloud.githubusercontent.com/assets/1781988/6241162/9b80d63e-b6cd-11e4-81ef-466bb8619118.png)

PD's
![download 5](https://cloud.githubusercontent.com/assets/1781988/6241166/9ecf5900-b6cd-11e4-9e82-8d8137b97f17.png)


So the results don't look promising. On the other hand, we have something like between a factor of 10 and 100 fewer real lenses than simulations. This means that the training process itself is going to be a lot noisier.

**Comment by cpadavis** [comment]
Probably the only other thing I could add to this little exercise is to try making similar-sized samples of the simulations (ie try training PLs on only 100ish simulations).

But I don't see much use in that so I am gleefully going to close this issue that I just opened a couple minutes ago. I went through this exercise mostly for future reference since this seems like a reasonable question to ask.

**Comment by drphilmarshall** [comment]
It'll be interesting to repeat this exercise after we do the next project
with more realistic/difficult sims. I guess the blue correlations will get
tighter, don't you?
